### PR TITLE
API Suggestions

### PR DESCRIPTION
**Pull request by ArthurCose**
Feel free to reject this PR, the goal is to get these suggestions out of the way in any form so they don't pop up later.

Changes:
- Removed `get_position` and `set_position` from entities
  - `get_position` + `set_position` are easily confused with tile position and make more sense in the context of working with the sprite
  - Did not seem as useful as other shorthands such as `set_texture` and `get_texture`
 - Reduced floating functions
   - Moved *_dir functions onto Direction. ex: `flip_x_dir` is `Direction.flip_x(direction)`
   - Replaced `create_move_event` with `MoveEvent.new()`
   - Replaced `drag(direction, count)` with `Drag.new(direction, count)`
   - Replaced `no_drag()` with `Drag.new()` and `Drag.None`

 Remaining issues I don't really mind leaving in:
 - `delete`/`is_deleted` is very confusing. Does not tell you if the entity is deleted from memory, just that it's in a dying state/exploding. `kill`/`was_killed` makes more sense to me.
 - `remove` is very confusing. Sounds as if I am removing the entity from the field temporarily, rather than queuing deleting/freeing.
 - `set_animation` does not mirror `get_animation`. Seems fine, it seems to replace the animation anyway. We could also just add taking in an actual animation as an overload if we ever wanted to.
 - `make_hit_props` could be a constructor/`HitProps.new`
 - `entity:shake_camera` might make more sense somewhere else.

### CODE REVIEW

**Comment by TheMaverickProgrammer** [comment]
- and replace it with what? this is used to provide a tile offset. Keep in mind the target audience using this are not programmers. Developing an API to help them describe their ideas in a non-software way goes a long way. 
- I like all of this except the drag function. I guess I can come to like `Drag.None` being == to `Drag.new()` aka `no_drag()`. My goal is to 1. reduce `new()`s 2. make this API friendly to non programmers 3. reduce typing
- `delete`/`is_deleted` goes back to non programmers. From the game's perspective, deleting is the act of blowing up the enemy. 
- I can see this perspective but there's no other way to remove something from a tile except by setting the tile itself to nullptr. What's a better alternative?
- Yeah the animation objects/components have a lot to be desired on the lua side. Haven't come up with a better way to address these
- I wanted less `.new()` calls myself since doesn't sol put this on the heap? I made sure lua was getting a copyable lvalue from C++.
- I'd like to hear and alternative though I don't see a problem with it myself.

**Comment by ArthurCose** [comment]
`:sprite():set_position()` exists, it's more clear to me as it describes setting a position/offset of a sprite, vs setting the tile center relative position of an entity.

Every UserType appears to be put on the heap.

`remove` doesn't remove entities from the field, it removes them from the game and permanently marks them as removed. Attempting to add the entity back will immediately eject the entity from what I can tell as will_remove_eof can't be set to false, and previously triggered freeing their memory (this is still true for lua in most cases). To actually remove an entity from just a tile you need to call `tile:remove_entity_by_id` (confusing meaning for remove as it depends on the context)

`shake_camera` doesn't seem like a problem to me either as it seems like we will always have access to some entity. It's just odd as the entity seems unrelated to the shaking and just relays the message. It could make more sense on field or even a camera object that has more controls. I do like how it is as a shorter way of causing the effect so that's why it's in my not important list.

**Comment by ArthurCose** [comment]
The test I had for UserTypes: 

```c++
#ifdef __unix__
#define LUA_USE_POSIX 1
#endif
#define SOL_ALL_SAFETIES_ON 1
#include <sol/sol.hpp>

struct Test {
    int value{};
    Test(int value) : value(value) {}
};

int main() {
  sol::state lua;
  lua.open_libraries(sol::lib::base);

  lua.new_usertype<Test>("Test",
    "make", [] { return Test(0); },
    "set", [](Test& t, int value) {
      t.value = value;
    },
    "get", [](Test& t) {
      return t.value;
    }
  );

  lua.script_file("test.lua");

  return 0;
}
```

```lua
local a = Test.make();
a:set(1)

b = a
b:set(2)

print(a:get(), b:get()) -- output: `2       2`
```

**Comment by Keristero** [comment]
you said it right there in the comment, `:sprite():set_offset()` sounds best to me

**Comment by TheMaverickProgrammer** [comment]
I don't believe `:sprite():set_offset()` works as a replacement. The `Entity` class is auto-updating the position based on movement type and elevation. It might be overwritten (haven't checked)

**Comment by TheMaverickProgrammer** [comment]
> 
> 
> The test I had for UserTypes:
> 
> ```c++
> #ifdef __unix__
> #define LUA_USE_POSIX 1
> #endif
> #define SOL_ALL_SAFETIES_ON 1
> #include <sol/sol.hpp>
> 
> struct Test {
>     int value{};
>     Test(int value) : value(value) {}
> };
> 
> int main() {
>   sol::state lua;
>   lua.open_libraries(sol::lib::base);
> 
>   lua.new_usertype<Test>("Test",
>     "make", [] { return Test(0); },
>     "set", [](Test& t, int value) {
>       t.value = value;
>     },
>     "get", [](Test& t) {
>       return t.value;
>     }
>   );
> 
>   lua.script_file("test.lua");
> 
>   return 0;
> }
> ```
> 
> ```lua
> local a = Test.make();
> a:set(1)
> 
> b = a
> b:set(2)
> 
> print(a:get(), b:get()) -- output: `2       2`
> ```

I don't know if this is proof it gets put on the heap or if sol/lua is intelligently referencing the var

**Comment by TheMaverickProgrammer** [comment]
> 
> 
> `:sprite():set_position()` exists, it's more clear to me as it describes setting a position/offset of a sprite, vs setting the tile center relative position of an entity.
> 
> Every UserType appears to be put on the heap.
> 
> `remove` doesn't remove entities from the field, it removes them from the game and permanently marks them as removed. Attempting to add the entity back will immediately eject the entity from what I can tell as will_remove_eof can't be set to false, and previously triggered freeing their memory (this is still true for lua in most cases). To actually remove an entity from just a tile you need to call `tile:remove_entity_by_id` (confusing meaning for remove as it depends on the context)
> 
> `shake_camera` doesn't seem like a problem to me either as it seems like we will always have access to some entity. It's just odd as the entity seems unrelated to the shaking and just relays the message. It could make more sense on field or even a camera object that has more controls. I do like how it is as a shorter way of causing the effect so that's why it's in my not important list.

what's the alt to `remove()` then for lua?

**Comment by ArthurCose** [comment]
Personally I would rename `delete`/`is_deleted` to `destroy`/`is_destroyed`, then rename `remove` to `delete`.

This is also in my "don't mind if it stays" so I'm not fighting for a change on this one.

**Comment by TheMaverickProgrammer** [comment]
> 
> 
> Personally I would rename `delete`/`is_deleted` to `destroy`/`is_destroyed`, then rename `remove` to `delete`.
> 
> This is also in my "don't mind if it stays" so I'm not fighting for a change on this one.

this is even more confusing for those of us in the C++ side of things. "Destroy" is no more clean than "delete was. What if we hide his function in lua and make an `Battle.Erase(entity)` function? This way it is explicit.

**Comment by TheMaverickProgrammer** [comment]
Off-site chat we came to the agreement to rename misleading `remove` and `will_remove_eof` functions to `erase` and `will_erase_eof`

**Comment by ArthurCose** [comment]
Wanting to confirm these as changes so I can update the branch:
 - `remove`/`will_remove_eof` as `erase`/`will_erase_eof` ✅
 - Keeping `delete`/`is_deleted` ✅
 - Keeping `set_position`/`get_position` on entities, but renaming to `set_offset`/`get_offset` on entities + scene/sprite nodes❓
 - Direction helpers on the Direction enum. ex: `Direction.flip_x(direction)`❓
 - Direction.new(direction, count)/Direction.new() + Direction.None❓
 - MoveEvent.new()❓
 - HitProps.new(damage, flags, element, aggressor, drag)❓
   - I didn't actually commit to this suggestion but I want to be able to drop this from convo through a yes/no
 
For the .new() functions, I don't see anything in the sol docs mentioning treating .new() as different. If anything maybe the [opposite](https://sol2.readthedocs.io/en/latest/api/usertype.html?highlight=factories#:~:text=Results%20from%20this%20function%20will%20be%20pushed%20into%20Lua%20according%20to%20the%20same%20rules%20as%20everything%20else.)

**Comment by TheMaverickProgrammer** [comment]
- approved
- approved
- approved
- approved
- approved
- approved
- approved

Thanks for the ref. Seems it all goes into the lua heap regardless. I guess SOL does some lifetime checks on our behalf and that's why we're able to used sharedptr and uniqueptr.

**Pull request merged**
