### PR TITLE
Upgrade OnlineArea

### PR DESCRIPTION
**Pull request by ArthurCose**
Adds the following features:

- Tiled maps using the tmx format!
  - Can define area name, background name, and song path
  - Flipping + Rotating tiles
  - Objects + collisions (Ellipse, Rectangle, Polygon)
  - More details in Server repo
- Receiving assets from the server with caching and cache invalidation
- Sharing custom avatars
- Tile, Object, and Navi interaction
- Creating Message, Question, and Quiz TextBoxes from the server with response packets
- Transferring between multiple areas on the same server
- Dynamic map updates from server
- Server controlled camera with queue
- Locking input from server
- Setting player position from server
- Connection stability
- Slightly more accurate facing calculation
- SpatialMap for actors implemented with spatial hashing
  - Can be swapped with a quadtree
  - Future work may include converting to a template to allow for Map to store objects

### CODE REVIEW

**Comment by TheMaverickProgrammer** [comment]
*cracks knucksles* alright here we go

**Comment by Keristero** [comment]
Hype, do you think we could do something like serving the map layouts, resources and music from an external website? I'd like to get back into making a website to mmbn map generator (web browser?) that supports this format.

I could host a server with a API that given a URL returns all the resources for a generated internet zone?

**Comment by TheMaverickProgrammer** [comment]
> 
> 
> Hype, do you think we could do something like serving the map layouts, resources and music from an external website? I'd like to get back into making a website to mmbn map generator (web browser?) that supports this format.
> 
> I could host a server with a API that given a URL returns all the resources for a generated internet zone?

The server will send the area assets over upon connection even custom ones. And it is dynamic so you can generate a map in the server and anyone connecting to it will see and play in your area.

**Comment by ArthurCose** [comment]
@Keristero I would like to have something like that be possible through the server's Lua scripting API (grabbing files from the internet and creating assets). Which should allow you to offload that work onto another server or generate it entirely on the server.

As @TheMaverickProgrammer mentioned the server is capable of dynamically creating maps, although currently, it's very limited. It's more suited for modifying existing maps.

At the very least you should currently be able to export your generated maps and use them on the server (and restart it between updates).

**Comment by TheMaverickProgrammer** [comment]
No offending items but some areas of improvement:
- You can check for byte order and flip the bytes around 
https://github.com/TheMaverickProgrammer/Bytepacker/blob/master/include/bytepacker.h#L12
https://github.com/TheMaverickProgrammer/Bytepacker/blob/master/include/bytepacker.h#L43

You can yoink the code that checks and flips from one of my tinker projects above

- Some sort of friendlier Otho/Iso projection math util. In my old netcode, I let the map project into isometric in the draw call only and that allowed me to do math/collision/placement of objects entirely in ortho projection space which made it really convenient as I didn't have to do much extra math at all. A utility function to reduce the amount of tile object placement I saw would be helpful.

I'm going to test and then if everything's good I'll begin the merge. Thanks again! Glad to have you contribute to make this project an awesome project!

**Comment by TheMaverickProgrammer** [comment]
@ArthurCose issues trying to compile:
- designated initializers require C++20. This project is on C++17
- M_PI is not standard-defined. I used `swoosh::ease::pi` in its place
- uint is not a type. I changed it to `unsigned int`
- to use std::array<> you need to include its header file first

I'll push my edits to your branch so the PR can receive them
testing with a successful build now

**Comment by TheMaverickProgrammer** [comment]
Couple of issues with live testing including crashes. I'll move those notes over to your branch and help debug them.

**Pull request merged**
